# https://travis-ci.org

sudo: required

language: cpp

dist: trusty

addons:
  apt:
    packages:
      - build-essential
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - cmake

cache:
  - apt
  - ccache

notifications:
  irc:
    channels: "chat.freenode.net#ppsspp"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository_slug}:%{branch} - %{message} %{build_url}"

matrix:
  include:
    - os: linux
      compiler: "gcc linux"
      env: PPSSPP_BUILD_TYPE=Linux
           CMAKE=TRUE
    - os: linux
      compiler: "gcc android"
      env: PPSSPP_BUILD_TYPE=Android
    - os: linux
      compiler: "gcc blackberry"
      env: PPSSPP_BUILD_TYPE=Blackberry
           CMAKE=TRUE
    - os: linux
      compiler: "gcc symbian"
      env: PPSSPP_BUILD_TYPE=Symbian
    - os: linux
      compiler: "clang linux"
      env: PPSSPP_BUILD_TYPE=Linux
           CMAKE=TRUE
    - os: linux
      compiler: "gcc qt"
      env: PPSSPP_BUILD_TYPE=Linux
           QT=TRUE
# Can't get iOS to work.
#    - os: osx
#      compiler: "clang ios"
#      env: PPSSPP_BUILD_TYPE=iOS
#           CMAKE=TRUE

before_install:
  - bash .travis.sh travis_before_install

install:
  - bash .travis.sh travis_install

script:
  - bash .travis.sh travis_script

after_success:
  - bash .travis.sh travis_after_success
