# https://travis-ci.org

sudo: required

language: cpp

dist: trusty

addons:
  apt:
    packages:
      - build-essential
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - cmake
      - aria2
      - ant
      - lib32stdc++6
      - lib32z1
      - lib32z1-dev
      - lib32bz2-1.0

cache:
  - apt
  - ccache

notifications:
  irc:
    channels: "chat.freenode.net#ppsspp"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository_slug}:%{branch} - %{message} %{build_url}"

matrix:
  include:
    - os: linux
      compiler: "gcc linux"
      env: PPSSPP_BUILD_TYPE=Linux
           CMAKE=TRUE
    - os: linux
      compiler: "gcc android-arm64-v8a"
      env: PPSSPP_BUILD_TYPE=Android
           APP_ABI=arm64-v8a
    - os: linux
      compiler: "gcc android-armeabi-v7a"
      env: PPSSPP_BUILD_TYPE=Android
           APP_ABI=armeabi-v7a
    - os: linux
      compiler: "gcc android-x86"
      env: PPSSPP_BUILD_TYPE=Android
           APP_ABI=x86
    - os: linux
      compiler: "gcc android-x86_64"
      env: PPSSPP_BUILD_TYPE=Android
           APP_ABI=x86_64
    - os: linux
      compiler: "gcc blackberry"
      env: PPSSPP_BUILD_TYPE=Blackberry
           CMAKE=TRUE
    - os: linux
      compiler: "gcc symbian"
      env: PPSSPP_BUILD_TYPE=Symbian
    - os: linux
      compiler: "clang linux"
      env: PPSSPP_BUILD_TYPE=Linux
           CMAKE=TRUE
    - os: linux
      compiler: "gcc qt"
      env: PPSSPP_BUILD_TYPE=Linux
           QT=TRUE
# Can't get iOS to work.
#    - os: osx
#      compiler: "clang ios"
#      env: PPSSPP_BUILD_TYPE=iOS
#           CMAKE=TRUE

before_install:
  - bash .travis.sh travis_before_install

install:
  - bash .travis.sh travis_install

script:
  - bash .travis.sh travis_script

after_success:
  - bash .travis.sh travis_after_success
